### ISSUE TITLE
[FR] define a specific sheet for report

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/senseexcel-reporting#32]
A feature request from consultant M.Wuest:

- a possibility to define which sheet is for report creation
For example, only a specific sheet. At the moment it will take all excel-sheets to create the report!

**Comment by konne** [comment]
@AlexanderGoerlich I like to reject that, because it would break that printing from Excel and SER delivers the same result. You can hide Excel sheet for calculations,.. this will be not printed.
Please discuss it and maybe this solves already the issue. Otherwise please describe the use case more detailed

**Comment by mossbeard** [comment]
Will not be implemented.
